// Generated by CoffeeScript 1.10.0
(function() {
  var Resource, async, mongoose;

  mongoose = require('mongoose');

  Resource = require('../../src/resourcejs/Resource');

  async = require('async');

  module.exports = function(app, model) {
    var resource;
    resource = Resource(app, '/offers/:offerId', 'Redemptions', model).rest({
      before: function(req, res, next) {
        req.body.offer = req.params.offerId;
        req.modelQuery = this.model.where('offer', req.params.offerId);
        return next();
      },
      after: function(req, res, next) {
        console.log("after");
        return next();
      }
    }).patch({
      before: function(req, res, next) {
        var result, traverse;
        traverse = require('../../src/traverse');
        if (!((req.body != null) && (req.body[0] != null) && (req.body[0].op != null))) {
          result = traverse(req.body[0], '', []);
          req.body[0] = result[0];
        }
        return next();
      }
    });
    resource.modelName = resource.modelName.substring(0, resource.modelName.length - 1);
    return resource;
  };

}).call(this);

//# sourceMappingURL=OfferRedemption.js.map
