// Generated by CoffeeScript 1.10.0
(function() {
  var Nested, Offer, Resource, mongoose;

  mongoose = require('mongoose');

  Resource = require('../../src/resourcejs/Resource');

  Offer = require('../../models/firefly/Offer').model;

  Nested = require('./helpers/Nested');

  module.exports = function(app, model) {
    var resource;
    resource = Resource(app, '/vehicles/:vehicleId', 'ServiceItems', model).rest({
      before: function(req, res, next) {
        req.body.vehicle = req.params.vehicleId;
        req.modelQuery = this.model.where('vehicle', req.params.vehicleId);
        return next();
      },
      after: function(req, res, next) {
        return Nested.find('serviceitem', Offer, 'offers', req.method, res.resource.item, function(error, result) {
          return next();
        });
      }
    }).patch({
      before: function(req, res, next) {
        var result, traverse;
        traverse = require('../../src/traverse');
        if (!((req.body != null) && (req.body[0] != null) && (req.body[0].op != null))) {
          result = traverse(req.body[0], '', []);
          req.body[0] = result[0];
        }
        return next();
      }
    });
    resource.modelName = resource.modelName.substring(0, resource.modelName.length - 1);
    return resource;
  };

}).call(this);

//# sourceMappingURL=VehicleServiceItem.js.map
