// Generated by CoffeeScript 1.10.0
(function() {
  var Nested, Offer, Resource, ServiceItem, mongoose;

  mongoose = require('mongoose');

  Resource = require('../../src/resourcejs/Resource');

  ServiceItem = require('../../models/firefly/ServiceItem').model;

  Offer = require('../../models/firefly/Offer').model;

  Nested = require('./helpers/Nested');

  module.exports = function(app, model) {
    var resource;
    resource = Resource(app, '', 'Vehicles', model).rest({
      after: function(req, res, next) {
        if ((req.headers != null) && (req.headers.nested != null) && (req.headers.nested === 'true' || req.headers.nested === true)) {
          console.log("finding service items");
          Nested.find('vehicle', ServiceItem, 'serviceitems', req.method, res.resource.item, function(error, result) {
            console.log("found service items: ");
            Nested.find('serviceitem', Offer, 'offers', req.method, res.resource.item, function(error, result) {
              console.log("found service item offers: ");
              next();
            });
          });
        } else {
          return next();
        }
      }
    });
    resource.modelName = resource.modelName.substring(0, resource.modelName.length - 1);
    return resource;
  };

}).call(this);

//# sourceMappingURL=Vehicle.js.map
