// Generated by CoffeeScript 1.10.0
(function() {
  var AdviceTemplateSchema, MaintenanceSchema, Mongoose, ObjectId, OfferTemplateSchema, TriggerableSchema;

  Mongoose = require('mongoose');

  require('mongoose-schema-extend');

  ObjectId = Mongoose.Schema.Types.ObjectId;

  TriggerableSchema = require('./Triggerable').schema;

  AdviceTemplateSchema = require('./AdviceTemplate').schema;

  OfferTemplateSchema = require('./OfferTemplate').schema;

  MaintenanceSchema = TriggerableSchema.extend({
    advice: [AdviceTemplateSchema],
    offers: [OfferTemplateSchema]
  });

  module.exports = {
    model: null,
    schema: MaintenanceSchema
  };

}).call(this);

//# sourceMappingURL=Maintenance.js.map
