// Generated by CoffeeScript 1.10.0
(function() {
  var MojioVehicleSchema, Mongoose, ObjectId, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ObjectId = require('mongoose').Schema.Types.ObjectId;

  MojioVehicleSchema = new Schema({
    vehicleId: String,
    serviceTemplateId: {
      type: Mongoose.Schema.Types.ObjectId,
      ref: 'ServiceTemplate',
      index: true,
      require: true
    }
  });

  module.exports = {
    model: Mongoose.model("MojioVehicle", MojioVehicleSchema),
    schema: MojioVehicleSchema
  };

}).call(this);

//# sourceMappingURL=MojioVehicle.js.map
