// Generated by CoffeeScript 1.10.0
(function() {
  var MaintenanceSchema, Mongoose, TaskTemplateSchema;

  Mongoose = require('mongoose');

  require('mongoose-schema-extend');

  MaintenanceSchema = require('./Maintenance').schema;

  TaskTemplateSchema = MaintenanceSchema.extend({});

  module.exports = {
    model: Mongoose.model("Task", TaskTemplateSchema),
    schema: TaskTemplateSchema
  };

}).call(this);

//# sourceMappingURL=TaskTemplate.js.map
