// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(app) {
    return app.post('/push', function(req, res) {
      console.log("Message: " + req.body.message);
      return res.json({
        ok: true,
        message: req.body.message
      });
    });
  };

}).call(this);

//# sourceMappingURL=PushTester.js.map
