// Generated by CoffeeScript 1.10.0
(function() {
  var Resource, mongoose;

  mongoose = require('mongoose');

  Resource = require('../../src/resourcejs/Resource');

  module.exports = function(app, model) {
    return Resource(app, '', 'ServiceTemplates', model).rest();
  };

}).call(this);

//# sourceMappingURL=ServiceTemplate.js.map
