// Generated by CoffeeScript 1.10.0
(function() {
  var Resource, mongoose;

  mongoose = require('mongoose');

  Resource = require('../../src/resourcejs/Resource');

  module.exports = function(app, model) {
    return Resource(app, '', 'Situations', model).patch({
      before: function(req, res, next) {
        var result, traverse;
        traverse = require('../../src/traverse');
        if (!((req.body != null) && (req.body[0] != null) && (req.body[0].op != null))) {
          result = traverse(req.body[0], '', []);
          req.body[0] = result[0];
        }
        return next();
      }
    }).get().put().post()["delete"]().index();
  };

}).call(this);

//# sourceMappingURL=Situation.js.map
