// Generated by CoffeeScript 1.10.0
(function() {
  var assert, expect, mongoose, should;

  should = require('should');

  assert = require('chai').assert;

  expect = require('chai').expect;

  mongoose = require('mongoose');

  require('mongoose-schema-extend');

  describe('Controller Tests', function() {
    return it('controllers load with the right naming scheme', function() {
      var Model, app, express, i, j, k, l, len, len1, len2, model, models, name, names, results;
      express = require('express');
      app = express();
      models = ['ServiceTemplates', 'Situations'];
      for (j = 0, len = models.length; j < len; j++) {
        name = models[j];
        model = require('../models/admin/' + name.slice(0, name.length - 1));
        Model = require('../controllers/admin/' + name.slice(0, name.length - 1))(app, model);
        expect(Model.modelName).to.equal(name);
        expect(Model.name).to.equal(name.toLowerCase());
        should.exist(Model.model);
      }
      models = ['ServiceItems', 'Chains', 'Offers', 'Redemptions', 'Vehicles'];
      for (k = 0, len1 = models.length; k < len1; k++) {
        name = models[k];
        model = require('../models/firefly/' + name.slice(0, name.length - 1));
        Model = require('../controllers/firefly/' + name.slice(0, name.length - 1))(app, model);
        expect(Model.modelName).to.equal(name);
        expect(Model.name).to.equal(name.toLowerCase());
        should.exist(Model.model);
      }
      models = ['ChainDealers', 'OfferRedemptions'];
      names = ['Dealers', 'Redemptions'];
      results = [];
      for (i = l = 0, len2 = models.length; l < len2; i = ++l) {
        name = models[i];
        Model = require('../controllers/firefly/' + name.slice(0, name.length - 1))(app, model);
        expect(Model.modelName).to.equal(names[i]);
        expect(Model.name).to.equal(names[i].toLowerCase());
        results.push(should.exist(Model.model));
      }
      return results;
    });
  });

}).call(this);

//# sourceMappingURL=ResourceControllers_Tests.js.map
