// Generated by CoffeeScript 1.10.0
(function() {
  var Mongoose, NotificationSchema, Schema;

  Mongoose = require('mongoose');

  require('mongoose-schema-extend');

  Schema = Mongoose.Schema;

  NotificationSchema = new Schema({
    message: String,
    token: String
  });

  module.exports = {
    model: Mongoose.model("Notification", NotificationSchema),
    schema: NotificationSchema
  };

}).call(this);

//# sourceMappingURL=Notification.js.map
