// Generated by CoffeeScript 1.10.0
(function() {
  var Mongoose, ObjectId, ReasonSchema, Schema, SendableSchema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ObjectId = Mongoose.Schema.Types.ObjectId;

  ReasonSchema = require('./Reason').schema;

  SendableSchema = new Schema({
    name: String,
    description: String,
    icon: String,
    artwork: String,
    tag: String,
    given: {
      type: Date,
      "default": Date.now
    },
    reasons: [ReasonSchema],
    times: Number,
    dismissed: {
      type: Date,
      "default": null
    }
  });

  module.exports = {
    model: null,
    schema: SendableSchema
  };

}).call(this);

//# sourceMappingURL=Sendable.js.map
