// Generated by CoffeeScript 1.10.0
(function() {
  var Mongoose, ObjectId, Schema, VehicleBase, VehicleSchema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ObjectId = require('mongoose').Schema.Types.ObjectId;

  require('mongoose-schema-extend');

  VehicleBase = new Schema({});

  VehicleSchema = VehicleBase.extend({
    mojioVehicleId: {
      type: String,
      unique: true
    },
    token: String,
    mojioUserId: {
      type: String,
      unique: false
    },
    dealer: {
      type: Mongoose.Schema.Types.ObjectId,
      ref: 'Dealer',
      index: true,
      require: false
    },
    serviceitems: [
      {
        type: Mongoose.Schema.Types.ObjectId,
        ref: 'ServiceItem',
        require: false
      }
    ]
  });

  module.exports = {
    model: Mongoose.model("Vehicle", VehicleSchema),
    schema: VehicleSchema
  };

}).call(this);

//# sourceMappingURL=Vehicle.js.map
