// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(RED) {
    var LowerCaseNode;
    LowerCaseNode = function(config) {
      var node;
      RED.nodes.createNode(this, config);
      node = this;
      this.on('input', function(msg) {
        msg.payload = msg.payload.toLowerCase();
        return node.send(msg);
      });
    };
    RED.nodes.registerType("lower-case2", LowerCaseNode);
  };

}).call(this);

//# sourceMappingURL=lower-case2.js.map
