// Generated by CoffeeScript 1.10.0
(function() {
  var Vehicle, async;

  async = require('async');

  Vehicle = require('../models/firefly/Vehicle').model;

  module.exports = function(app) {
    app.use(function(req, res, next) {
      return next();
    });
  };

}).call(this);

//# sourceMappingURL=auth.js.map
